# Generated by Django 4.2.1 on 2023-05-21 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_rename_products_order_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='date_create',
            new_name='date_created',
        ),
    ]
